-- Request Assisted Search schema for the Karnataka 2002 voter search website.
-- Apply in the Supabase SQL editor after creating your project.
-- This version is designed for the existing static site and public form flow.

create extension if not exists pgcrypto;

create table if not exists public.search_requests (
  id bigint generated by default as identity primary key,
  order_id text unique,
  created_at timestamptz not null default now(),
  applicant_name text not null,
  mobile text not null,
  email text,
  primary_voter_id text not null,
  secondary_voter_id text,
  old_voter_id text,
  has_old_voter_id boolean not null default false,
  knows_neighbor boolean not null default false,
  neighbor_found_in_2002 boolean,
  neighbor_name text,
  neighbor_locality text,
  neighbor_voter_id text,
  neighbor_ac_number text,
  neighbor_part_number text,
  neighbor_serial_number text,
  neighbor_found_screenshot_url text,
  declaration_accepted boolean not null default false,
  primary_front_url text not null,
  primary_back_url text not null,
  secondary_front_url text,
  secondary_back_url text,
  old_front_url text,
  old_back_url text,
  status text not null default 'NEW',
  assigned_volunteer text,
  assigned_date timestamptz,
  ac_number text,
  part_number text,
  serial_number text,
  result_status text,
  remarks text,
  completed_at timestamptz,
  submission_key uuid not null default gen_random_uuid(),
  constraint search_requests_status_check check (status in ('NEW', 'ASSIGNED', 'COMPLETED', 'NOT_FOUND')),
  constraint search_requests_result_status_check check (result_status is null or result_status in ('FOUND', 'NOT_FOUND')),
  constraint search_requests_mobile_check check (mobile ~ '^[0-9]{10}$')
);

create unique index if not exists search_requests_submission_key_idx on public.search_requests (submission_key);
create index if not exists search_requests_order_id_idx on public.search_requests (order_id);
create index if not exists search_requests_mobile_idx on public.search_requests (mobile);
create index if not exists search_requests_status_idx on public.search_requests (status);
create index if not exists search_requests_assigned_volunteer_idx on public.search_requests (assigned_volunteer);

alter table public.search_requests add column if not exists neighbor_ac_number text;
alter table public.search_requests add column if not exists neighbor_part_number text;
alter table public.search_requests add column if not exists neighbor_serial_number text;
alter table public.search_requests add column if not exists neighbor_found_screenshot_url text;
alter table public.search_requests add column if not exists kannada_roll_validated boolean;
alter table public.search_requests add column if not exists details_cleared_at timestamptz;

create sequence if not exists public.search_request_order_seq start 1;

create or replace function public.generate_search_request_order_id()
returns trigger
language plpgsql
as $$
begin
  if new.order_id is null or trim(new.order_id) = '' then
    new.order_id := 'VSR-' || lpad(nextval('public.search_request_order_seq')::text, 6, '0');
  end if;
  return new;
end;
$$;

drop trigger if exists trg_generate_search_request_order_id on public.search_requests;
create trigger trg_generate_search_request_order_id
before insert on public.search_requests
for each row
execute function public.generate_search_request_order_id();

create table if not exists public.request_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  display_name text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_request_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.request_admins
    where user_id = uid
      and is_active = true
  );
$$;

revoke all on public.search_requests from anon, authenticated;
revoke all on public.request_admins from anon, authenticated;
grant select, update on public.search_requests to authenticated;
grant select on public.request_admins to authenticated;

alter table public.search_requests enable row level security;
alter table public.request_admins enable row level security;

drop policy if exists "request admins can read requests" on public.search_requests;
create policy "request admins can read requests"
on public.search_requests
for select
to authenticated
using (public.is_request_admin(auth.uid()));

drop policy if exists "request admins can update requests" on public.search_requests;
create policy "request admins can update requests"
on public.search_requests
for update
to authenticated
using (public.is_request_admin(auth.uid()))
with check (public.is_request_admin(auth.uid()));

drop policy if exists "request admins can read admin table" on public.request_admins;
create policy "request admins can read admin table"
on public.request_admins
for select
to authenticated
using (public.is_request_admin(auth.uid()));

create or replace function public.public_create_search_request(
  applicant_name text,
  mobile text,
  email text default null,
  primary_voter_id text default null,
  secondary_voter_id text default null,
  old_voter_id text default null,
  has_old_voter_id boolean default false,
  knows_neighbor boolean default false,
  neighbor_found_in_2002 boolean default null,
  neighbor_name text default null,
  neighbor_locality text default null,
  neighbor_voter_id text default null,
  neighbor_ac_number text default null,
  neighbor_part_number text default null,
  neighbor_serial_number text default null,
  neighbor_found_screenshot_url text default null,
  declaration_accepted boolean default false,
  primary_front_url text default null,
  primary_back_url text default null,
  secondary_front_url text default null,
  secondary_back_url text default null,
  old_front_url text default null,
  old_back_url text default null,
  submission_key text default null
)
returns table (id bigint, order_id text, status text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_mobile text;
  v_record public.search_requests%rowtype;
begin
  v_mobile := regexp_replace(coalesce(mobile, ''), '\D', '', 'g');
  if applicant_name is null or trim(applicant_name) = '' then
    raise exception 'Applicant name is required';
  end if;
  if length(v_mobile) <> 10 then
    raise exception 'A valid 10-digit mobile number is required';
  end if;
  if primary_voter_id is null or trim(primary_voter_id) = '' then
    raise exception 'Primary voter ID is required';
  end if;
  if primary_front_url is null or trim(primary_front_url) = '' then
    raise exception 'Primary voter ID front image is required';
  end if;
  if primary_back_url is null or trim(primary_back_url) = '' then
    raise exception 'Primary voter ID back image is required';
  end if;
  if declaration_accepted is distinct from true then
    raise exception 'Declaration must be accepted';
  end if;

  insert into public.search_requests (
    applicant_name,
    mobile,
    email,
    primary_voter_id,
    secondary_voter_id,
    old_voter_id,
    has_old_voter_id,
    knows_neighbor,
    neighbor_found_in_2002,
    neighbor_name,
    neighbor_locality,
    neighbor_voter_id,
    neighbor_ac_number,
    neighbor_part_number,
    neighbor_serial_number,
    neighbor_found_screenshot_url,
    declaration_accepted,
    primary_front_url,
    primary_back_url,
    secondary_front_url,
    secondary_back_url,
    old_front_url,
    old_back_url,
    submission_key
  )
  values (
    trim(applicant_name),
    v_mobile,
    nullif(trim(email), ''),
    trim(primary_voter_id),
    nullif(trim(secondary_voter_id), ''),
    nullif(trim(old_voter_id), ''),
    coalesce(has_old_voter_id, false),
    coalesce(knows_neighbor, false),
    neighbor_found_in_2002,
    nullif(trim(neighbor_name), ''),
    nullif(trim(neighbor_locality), ''),
    nullif(trim(neighbor_voter_id), ''),
    nullif(trim(neighbor_ac_number), ''),
    nullif(trim(neighbor_part_number), ''),
    nullif(trim(neighbor_serial_number), ''),
    nullif(trim(neighbor_found_screenshot_url), ''),
    true,
    trim(primary_front_url),
    trim(primary_back_url),
    nullif(trim(secondary_front_url), ''),
    nullif(trim(secondary_back_url), ''),
    nullif(trim(old_front_url), ''),
    nullif(trim(old_back_url), ''),
    coalesce(nullif(submission_key, '')::uuid, gen_random_uuid())
  )
  returning * into v_record;

  return query select v_record.id, v_record.order_id, v_record.status;
end;
$$;

grant execute on function public.public_create_search_request(
  text, text, text, text, text, text, boolean, boolean, boolean, text, text, text, text, text, text, text, boolean,
  text, text, text, text, text, text, text
) to anon, authenticated;

drop function if exists public.public_get_search_request_status(text, text);
create or replace function public.public_get_search_request_status(
  p_order_id text,
  p_mobile text
)
returns table (
  order_id text,
  created_at timestamptz,
  status text,
  result_status text,
  completed_at timestamptz,
  ac_number text,
  part_number text,
  serial_number text
)
language sql
security definer
set search_path = public
as $$
  select
    sr.order_id,
    sr.created_at,
    sr.status,
    sr.result_status,
    sr.completed_at,
    sr.ac_number,
    sr.part_number,
    sr.serial_number
  from public.search_requests sr
  where sr.order_id = upper(trim(p_order_id))
    and sr.mobile = regexp_replace(coalesce(p_mobile, ''), '\D', '', 'g')
  limit 1;
$$;

grant execute on function public.public_get_search_request_status(text, text) to anon, authenticated;

create or replace function public.admin_get_request_dashboard_stats()
returns table (
  total_found_voter_ids bigint,
  top_volunteer text,
  top_volunteer_found_count bigint
)
language sql
security definer
set search_path = public
as $$
  with admin_check as (
    select public.is_request_admin(auth.uid()) as allowed
  ),
  found_rows as (
    select sr.primary_voter_id, sr.assigned_volunteer
    from public.search_requests sr
    join admin_check ac on ac.allowed
    where sr.status = 'COMPLETED'
      and coalesce(sr.result_status, '') = 'FOUND'
  ),
  volunteer_ranking as (
    select
      assigned_volunteer,
      count(*)::bigint as found_count
    from found_rows
    where assigned_volunteer is not null
      and trim(assigned_volunteer) <> ''
    group by assigned_volunteer
  ),
  top_result as (
    select assigned_volunteer, found_count
    from volunteer_ranking
    order by found_count desc, assigned_volunteer asc
    limit 1
  )
  select
    (select count(distinct primary_voter_id)::bigint from found_rows),
    (select assigned_volunteer from top_result),
    coalesce((select found_count from top_result), 0::bigint);
$$;

grant execute on function public.admin_get_request_dashboard_stats() to authenticated;

create or replace function public.admin_cleanup_found_requests()
returns table (cleared_count bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count bigint;
begin
  if not public.is_request_admin(auth.uid()) then
    raise exception 'Only request admins can clear completed requests';
  end if;

  update public.search_requests
  set
    email = null,
    secondary_voter_id = null,
    old_voter_id = null,
    has_old_voter_id = false,
    knows_neighbor = false,
    neighbor_found_in_2002 = null,
    neighbor_name = null,
    neighbor_locality = null,
    neighbor_voter_id = null,
    neighbor_ac_number = null,
    neighbor_part_number = null,
    neighbor_serial_number = null,
    neighbor_found_screenshot_url = null,
    primary_front_url = '',
    primary_back_url = '',
    secondary_front_url = null,
    secondary_back_url = null,
    old_front_url = null,
    old_back_url = null,
    remarks = null,
    details_cleared_at = now()
  where status = 'COMPLETED'
    and coalesce(result_status, '') = 'FOUND'
    and details_cleared_at is null;

  get diagnostics v_count = row_count;
  return query select v_count;
end;
$$;

grant execute on function public.admin_cleanup_found_requests() to authenticated;

-- Storage bucket for uploaded images.
insert into storage.buckets (id, name, public)
values ('request-assist-uploads', 'request-assist-uploads', true)
on conflict (id) do nothing;

drop policy if exists "public can upload request images" on storage.objects;
create policy "public can upload request images"
on storage.objects
for insert
to anon, authenticated
with check (bucket_id = 'request-assist-uploads');

drop policy if exists "admins can manage request images" on storage.objects;
create policy "admins can manage request images"
on storage.objects
for all
to authenticated
using (
  bucket_id = 'request-assist-uploads'
  and public.is_request_admin(auth.uid())
)
with check (
  bucket_id = 'request-assist-uploads'
  and public.is_request_admin(auth.uid())
);

comment on table public.search_requests is 'Assisted-search requests submitted by citizens who need manual help locating 2002 Karnataka electoral records.';
