_CURRENT_AC_MASTER = {
    1: {"en": "Nippani", "kn": "ನಿಪ್ಪಾಣಿ"},
    2: {"en": "Chikkodi-sadalga", "kn": "ಚಿಕ್ಕೋಡಿ-ಸದಲಗಾ"},
    3: {"en": "Athani", "kn": "ಅಥಣಿ"},
    4: {"en": "Kagwad", "kn": "ಕಾಗವಾಡ"},
    5: {"en": "Kudachi", "kn": "ಕುಡಚಿ"},
    6: {"en": "Raybag", "kn": "ರಾಯಭಾಗ"},
    7: {"en": "Hukkeri", "kn": "ಹುಕ್ಕೇರಿ"},
    8: {"en": "Arabhavi", "kn": "ಅರಭಾವಿ"},
    9: {"en": "Gokak", "kn": "ಗೋಕಾಕ"},
    10: {"en": "Yemkanamardi", "kn": "ಯಮಕನಮರಡಿ"},
    11: {"en": "Belgaum Uttar", "kn": "ಬೆಳಗಾವಿ ಉತ್ತರ"},
    12: {"en": "Belgaum Dakshin", "kn": "ಬೆಳಗಾವಿ ದಕ್ಷಿಣ"},
    13: {"en": "Belgaum Rural", "kn": "ಬೆಳಗಾವಿ ಗ್ರಾಮಾಂತರ"},
    14: {"en": "Khanapur", "kn": "ಖಾನಾಪೂರ"},
    15: {"en": "Kittur", "kn": "ಕಿತ್ತೂರು"},
    16: {"en": "Bailahongal", "kn": "ಬೈಲಹೊಂಗಲ"},
    17: {"en": "Saundatti Yellamma", "kn": "ಸವದತ್ತಿ ಯಲ್ಲಮ್ಮ"},
    18: {"en": "Ramdurg", "kn": "ರಾಮದುರ್ಗ"},
    19: {"en": "Mudhol", "kn": "ಮುಧೋಳ"},
    20: {"en": "Terdal", "kn": "ತೇರದಾಳ"},
    21: {"en": "Jamkhandi", "kn": "ಜಮಖಂಡಿ"},
    22: {"en": "Bilgi", "kn": "ಬೀಳಗಿ"},
    23: {"en": "Badami", "kn": "ಬಾದಾಮಿ"},
    24: {"en": "Bagalkot", "kn": "ಬಾಗಲಕೋಟೆ"},
    25: {"en": "Hungund", "kn": "ಹುನಗುಂದ"},
    26: {"en": "Muddebihal", "kn": "ಮುದ್ದೇಬಿಹಾಳ"},
    27: {"en": "Devara Hippargi", "kn": "ದೇವರ ಹಿಪ್ಪರಗಿ"},
    28: {"en": "Basavana Bagevadi", "kn": "ಬಸವನ ಬಾಗೇವಾಡಿ"},
    29: {"en": "Babaleshwar", "kn": "ಬಬಲೇಶ್ವರ್\u200c"},
    30: {"en": "Bijapur City", "kn": "ವಿಜಾಪೂರ ನಗರ"},
    31: {"en": "Nagthan", "kn": "ನಾಗಠಾಣ"},
    32: {"en": "Indi", "kn": "ಇಂಡಿ"},
    33: {"en": "Sindgi", "kn": "ಸಿಂಧಗಿ"},
    34: {"en": "Afzalpur", "kn": "ಅಫಜಲಪೂರ"},
    35: {"en": "Jevargi", "kn": "ಜೇವರ್ಗಿ"},
    36: {"en": "Shorapur", "kn": "ಶೋರಾಪೂರ"},
    37: {"en": "Shahapur", "kn": "ಶಹಾಪೂರ"},
    38: {"en": "Yadgir", "kn": "ಯಾದಗಿರಿ"},
    39: {"en": "Gurmitkal", "kn": "ಗುರುಮಿಟಕಲ್\u200c"},
    40: {"en": "Chittapur", "kn": "ಚಿತ್ತಾಪೂರ"},
    41: {"en": "Sedam", "kn": "ಸೇಡಂ"},
    42: {"en": "Chincholi", "kn": "ಚಿಂಚೋಳಿ"},
    43: {"en": "Gulbarga Rural", "kn": "ಗುಲಬರ್ಗಾ ಗ್ರಾಮಾಂತರ"},
    44: {"en": "Gulbarga Dakshin", "kn": "ಗುಲಬರ್ಗಾ ದಕ್ಷಿಣ"},
    45: {"en": "Gulbarga Uttar", "kn": "ಗುಲಬರ್ಗಾ ಉತ್ತರ"},
    46: {"en": "Aland", "kn": "ಅಳಂದ"},
    47: {"en": "Basavakalyan", "kn": "ಬಸವಕಲ್ಯಾಣ"},
    48: {"en": "Humnabad", "kn": "ಹುಮನಾಬಾದ"},
    49: {"en": "Bidar South", "kn": "ಬೀದರ್\u200c ದಕ್ಷಿಣ"},
    50: {"en": "Bidar", "kn": "ಬೀದರ್\u200c"},
    51: {"en": "Bhalki", "kn": "ಭಾಲ್ಕಿ"},
    52: {"en": "Aurad", "kn": "ಔರಾದ"},
    53: {"en": "Raichur Rural", "kn": "ರಾಯಚೂರು ಗ್ರಾಮಾಂತರ"},
    54: {"en": "Raichur", "kn": "ರಾಯಚೂರು"},
    55: {"en": "Manvi", "kn": "ಮಾನ್ವಿ"},
    56: {"en": "Devadurga", "kn": "ದೇವದುರ್ಗ"},
    57: {"en": "Lingsugur", "kn": "ಲಿಂಗಸುಗೂರು"},
    58: {"en": "Sindhanur", "kn": "ಸಿಂಧನೂರು"},
    59: {"en": "Maski", "kn": "ಮಸ್ಕಿ"},
    60: {"en": "Kushtagi", "kn": "ಕುಷ್ಟಗಿ"},
    61: {"en": "Kanakagiri", "kn": "ಕನಕಗಿರಿ"},
    62: {"en": "Gangavathi", "kn": "ಗಂಗಾವತಿ"},
    63: {"en": "Yelburga", "kn": "ಯಲಬುರ್ಗಾ"},
    64: {"en": "Koppal", "kn": "ಕೊಪ್ಪಳ"},
    65: {"en": "Shirahatti", "kn": "ಶಿರಹಟ್ಟಿ"},
    66: {"en": "Gadag", "kn": "ಗದಗ"},
    67: {"en": "Ron", "kn": "ರೋಣ"},
    68: {"en": "Nargund", "kn": "ನರಗುಂದ"},
    69: {"en": "Navalgund", "kn": "ನವಲಗುಂದ"},
    70: {"en": "Kundgol", "kn": "ಕುಂದಗೋಳ"},
    71: {"en": "Dharwad", "kn": "ಧಾರವಾಡ"},
    72: {"en": "Hubli-dharwad-east", "kn": "ಹುಬ್ಬಳ್ಳಿ - ಧಾರವಾಡ -ಪೂರ್ವ"},
    73: {"en": "Hubli-dharwad-central", "kn": "ಹುಬ್ಬಳ್ಳಿ-ಧಾರವಾಡ ಕೇಂದ್ರ"},
    74: {"en": "Hubli-dharwad-west", "kn": "ಹುಬ್ಬಳ್ಳಿ-ಧಾರವಾಡ-ಪಶ್ಚಿಮ"},
    75: {"en": "Kalaghatgi", "kn": "ಕಲಘಟಗಿ"},
    76: {"en": "Haliyal", "kn": "ಹಳಿಯಾಳ"},
    77: {"en": "Karwar", "kn": "ಕಾರವಾರ"},
    78: {"en": "Kumta", "kn": "ಕುಮಟಾ"},
    79: {"en": "Bhatkal", "kn": "ಭಟ್ಕಳ"},
    80: {"en": "Sirsi", "kn": "ಸಿರ್ಸಿ"},
    81: {"en": "Yellapur", "kn": "ಯಲ್ಲಾಪುರ"},
    82: {"en": "Hangal", "kn": "ಹಾನಗಲ್"},
    83: {"en": "Shiggaon", "kn": "ಶಿಗ್ಗಾಂವ"},
    84: {"en": "Haveri", "kn": "ಹಾವೇರಿ"},
    85: {"en": "Byadgi", "kn": "ಬ್ಯಾಡಗಿ"},
    86: {"en": "Hirekerur", "kn": "ಹಿರೇಕೆರೂರು"},
    87: {"en": "Ranebennur", "kn": "ರಾಣೆಬೆನ್ನೂರು"},
    88: {"en": "Hadagali", "kn": "ಹಡಗಲಿ"},
    89: {"en": "Hagaribommanahalli", "kn": "ಹಗರಿಬೊಮ್ಮನಹಳ್ಳಿ"},
    90: {"en": "Vijayanagara", "kn": "ವಿಜಯನಗರ"},
    91: {"en": "Kampli", "kn": "ಕಂಪ್ಲಿ"},
    92: {"en": "Siraguppa", "kn": "ಸಿರುಗುಪ್ಪ"},
    93: {"en": "Bellary", "kn": "ಬಳ್ಳಾರಿ"},
    94: {"en": "Bellary City", "kn": "ಬಳ್ಳಾರಿ ನಗರ"},
    95: {"en": "Sandur", "kn": "ಸಂಡೂರು"},
    96: {"en": "Kudligi", "kn": "ಕೂಡ್ಲಿಗಿ"},
    97: {"en": "Molakalmuru", "kn": "ಮೊಳಕಾಲ್ಮೂರು"},
    98: {"en": "Challakere", "kn": "ಚಳ್ಳಕೆರೆ"},
    99: {"en": "Chitradurga", "kn": "ಚಿತ್ರದುರ್ಗ"},
    100: {"en": "Hiriyur", "kn": "ಹಿರಿಯೂರು"},
    101: {"en": "Hosadurga", "kn": "ಹೊಸದುರ್ಗ"},
    102: {"en": "Holalkere", "kn": "ಹೊಳಲ್ಕೆರೆ"},
    103: {"en": "Jagalur", "kn": "ಜಗಳೂರು"},
    104: {"en": "Harapanahalli", "kn": "ಹರಪನಹಳ್ಳಿ"},
    105: {"en": "Harihar", "kn": "ಹರಿಹರ"},
    106: {"en": "Davanagere North", "kn": "ದಾವಣಗೆರೆ ಉತ್ತರ"},
    107: {"en": "Davanagere South", "kn": "ದಾವಣಗೆರೆ ದಕ್ಷಿಣ"},
    108: {"en": "Mayakonda", "kn": "ಮಾಯಕೊಂಡ"},
    109: {"en": "Channagiri", "kn": "ಚನ್ನಗಿರಿ"},
    110: {"en": "Honnali", "kn": "ಹೊನ್ನಾಳಿ"},
    111: {"en": "Shimoga Rural", "kn": "ಶಿವಮೊಗ್ಗ ಗ್ರಾಮಾಂತರ"},
    112: {"en": "Bhadravathi", "kn": "ಭದ್ರಾವತಿ"},
    113: {"en": "Shimoga", "kn": "ಶಿವಮೊಗ್ಗ"},
    114: {"en": "Tirthahalli", "kn": "ತೀರ್ಥಹಳ್ಳಿ"},
    115: {"en": "Shikaripura", "kn": "ಶಿಕಾರಿಪುರ"},
    116: {"en": "Sorab", "kn": "ಸೊರಬ"},
    117: {"en": "Sagar", "kn": "ಸಾಗರ"},
    118: {"en": "Baindur", "kn": "ಬೈಂದೂರು"},
    119: {"en": "Kundapur", "kn": "ಕುಂದಾಪುರ"},
    120: {"en": "Udupi", "kn": "ಉಡುಪಿ"},
    121: {"en": "Kaup", "kn": "ಕಾಪು"},
    122: {"en": "Karkala", "kn": "ಕಾರ್ಕಳ"},
    123: {"en": "Sringeri", "kn": "ಶೃಂಗೇರಿ"},
    124: {"en": "Mudigere", "kn": "ಮೂಡಿಗೆರೆ"},
    125: {"en": "Chickamagalur", "kn": "ಚಿಕ್ಕಮಗಳೂರು"},
    126: {"en": "Tarikere", "kn": "ತರೀಕೆರೆ"},
    127: {"en": "Kadur", "kn": "ಕಡೂರು"},
    128: {"en": "Chikknayakanhalli", "kn": "ಚಿಕ್ಕನಾಯಕನಹಳ್ಳಿ"},
    129: {"en": "Tiptur", "kn": "ತಿಪಟೂರು"},
    130: {"en": "Turuvekere", "kn": "ತುರುವೇಕೆರೆ"},
    131: {"en": "Kunigal", "kn": "ಕುಣಿಗಲ್\u200c"},
    132: {"en": "Tumkur City", "kn": "ತುಮಕೂರು ನಗರ"},
    133: {"en": "Tumkur Rural", "kn": "ತುಮಕೂರು ಗ್ರಾಮಾಂತರ"},
    134: {"en": "Koratagere", "kn": "ಕೊರಟಗೆರೆ"},
    135: {"en": "Gubbi", "kn": "ಗುಬ್ಬಿ"},
    136: {"en": "Sira", "kn": "ಶಿರಾ"},
    137: {"en": "Pavagada", "kn": "ಪಾವಗಡ"},
    138: {"en": "Madhugiri", "kn": "ಮಧುಗಿರಿ"},
    139: {"en": "Gauribidanur", "kn": "ಗೌರಿಬಿದನೂರು"},
    140: {"en": "Bagepalli", "kn": "ಬಾಗೇಪಲ್ಲಿ"},
    141: {"en": "Chikkaballapur", "kn": "ಚಿಕ್ಕಬಳ್ಳಾಪುರ"},
    142: {"en": "Sidlaghatta", "kn": "ಶಿಡ್ಲಘಟ್ಟ"},
    143: {"en": "Chintamani", "kn": "ಚಿಂತಾಮಣಿ"},
    144: {"en": "Srinivasapur", "kn": "ಶ್ರೀನಿವಾಸಪುರ"},
    145: {"en": "Mulbagal", "kn": "ಮುಳಬಾಗಿಲು"},
    146: {"en": "Kolar Gold Field", "kn": "ಕೆ.ಜಿ.ಎಫ್\u200c"},
    147: {"en": "Bangarapet", "kn": "ಬಂಗಾರಪೇಟೆ"},
    148: {"en": "Kolar", "kn": "ಕೋಲಾರ"},
    149: {"en": "Malur", "kn": "ಮಾಲೂರು"},
    150: {"en": "Yelahanka", "kn": "ಯಲಹಂಕ"},
    151: {"en": "K.r. Pura", "kn": "ಕೆ.ಆರ್\u200c.ಪುರ"},
    152: {"en": "Byatarayanapura", "kn": "ಬ್ಯಾಟರಾಯನಪುರ"},
    153: {"en": "Yeshwanthapura", "kn": "ಯಶವಂತಪುರ"},
    154: {"en": "Rajarajeshwarinagar", "kn": "ರಾಜರಾಜೇಶ್ವರಿನಗರ"},
    155: {"en": "Dasarahalli", "kn": "ದಾಸರಹಳ್ಳಿ"},
    156: {"en": "Mahalakshmi Layout", "kn": "ಮಹಾಲಕ್ಷ್ಮಿ ಬಡಾವಣೆ"},
    157: {"en": "Malleshwaram", "kn": "ಮಲ್ಲೇಶ್ವರಂ"},
    158: {"en": "Hebbal", "kn": "ಹೆಬ್ಬಾಳ"},
    159: {"en": "Pulakeshinagar", "kn": "ಪುಲಕೇಶಿನಗರ"},
    160: {"en": "Sarvagnanagar", "kn": "ಸರ್ವಜ್ಞ ನಗರ"},
    161: {"en": "C.v. Ramannnagar", "kn": "ಸಿ.ವಿ. ರಾಮನ್\u200c ನಗರ"},
    162: {"en": "Shivajinagar", "kn": "ಶಿವಾಜಿನಗರ"},
    163: {"en": "Shantinagar", "kn": "ಶಾಂತಿನಗರ"},
    164: {"en": "Gandhinagar", "kn": "ಗಾಂಧಿನಗರ"},
    165: {"en": "Rajajinagar", "kn": "ರಾಜಾಜಿನಗರ"},
    166: {"en": "Govindarajanagar", "kn": "ಗೋವಿಂದರಾಜ ನಗರ"},
    167: {"en": "Vijayanagar", "kn": "ವಿಜಯನಗರ"},
    168: {"en": "Chamrajapet", "kn": "ಚಾಮರಾಜಪೇಟೆ"},
    169: {"en": "Chickpet", "kn": "ಚಿಕ್ಕಪೇಟೆ"},
    170: {"en": "Basavanagudi", "kn": "ಬಸವನಗುಡಿ"},
    171: {"en": "Padmanabanagar", "kn": "ಪದ್ಮನಾಭನಗರ"},
    172: {"en": "B.t.m Layout", "kn": "ಬಿ.ಟಿ.ಎಂ ಲೇಔಟ್"},
    173: {"en": "Jayanagar", "kn": "ಜಯನಗರ"},
    174: {"en": "Mahadevapura", "kn": "ಮಹದೇವಪುರ"},
    175: {"en": "Bommanahalli", "kn": "ಬೊಮ್ಮನಹಳ್ಳಿ"},
    176: {"en": "Bangalore South", "kn": "ಬೆಂಗಳೂರು ದಕ್ಷಿಣ"},
    177: {"en": "Anekal", "kn": "ಆನೇಕಲ್\u200c"},
    178: {"en": "Hosakote", "kn": "ಹೊಸಕೋಟೆ"},
    179: {"en": "Devanahalli", "kn": "ದೇವನಹಳ್ಳಿ"},
    180: {"en": "Doddaballapur", "kn": "ದೊಡ್ಡಬಳ್ಳಾಪುರ"},
    181: {"en": "Nelamangala", "kn": "ನೆಲಮಂಗಲ"},
    182: {"en": "Magadi", "kn": "ಮಾಗಡಿ"},
    183: {"en": "Ramanagaram", "kn": "ರಾಮನಗರಂ"},
    184: {"en": "Kanakapura", "kn": "ಕನಕಪುರ"},
    185: {"en": "Channapatna", "kn": "ಚನ್ನಪಟ್ಟಣ"},
    186: {"en": "Malavalli", "kn": "ಮಳವಳ್ಳಿ"},
    187: {"en": "Maddur", "kn": "ಮದ್ದೂರು"},
    188: {"en": "Melukote", "kn": "ಮೇಲುಕೋಟೆ"},
    189: {"en": "Mandya", "kn": "ಮಂಡ್ಯ"},
    190: {"en": "Shrirangapattana", "kn": "ಶ್ರೀರಂಗಪಟ್ಟಣ"},
    191: {"en": "Nagamangala", "kn": "ನಾಗಮಂಗಲ"},
    192: {"en": "Krishnarajpet", "kn": "ಕೆ.ಆರ್\u200c .ಪೇಟೆ"},
    193: {"en": "Shravanabelagola", "kn": "ಶ್ರವಣಬೆಳಗೊಳ"},
    194: {"en": "Arsikere", "kn": "ಅರಸೀಕೆರೆ"},
    195: {"en": "Belur", "kn": "ಬೇಲೂರು"},
    196: {"en": "Hassan", "kn": "ಹಾಸನ"},
    197: {"en": "Holenarasipur", "kn": "ಹೊಳೇನರಸೀಪುರ"},
    198: {"en": "Arakalgud", "kn": "ಅರಕಲಗೂಡು"},
    199: {"en": "Sakaleshpur", "kn": "ಸಕಲೇಶಪುರ"},
    200: {"en": "Belthangady", "kn": "ಬೆಳ್ತಂಗಡಿ"},
    201: {"en": "Moodabidri", "kn": "ಮೂಡಬಿದ್ರಿ"},
    202: {"en": "Mangalore City North", "kn": "ಮಂಗಳೂರು ನಗರ ಉತ್ತರ"},
    203: {"en": "Mangalore City South", "kn": "ಮಂಗಳೂರು ನಗರ ದಕ್ಷಿಣ"},
    204: {"en": "Mangalore", "kn": "ಮಂಗಳೂರು"},
    205: {"en": "Bantwal", "kn": "ಬಂಟ್ವಾಳ"},
    206: {"en": "Puttur", "kn": "ಪುತ್ತೂರು"},
    207: {"en": "Sullia", "kn": "ಸುಳ್ಯ"},
    208: {"en": "Madikeri", "kn": "ಮಡಿಕೇರಿ"},
    209: {"en": "Virajpet", "kn": "ವೀರಾಜಪೇಟೆ"},
    210: {"en": "Piriyapatna", "kn": "ಪಿರಿಯಾಪಟ್ಟಣ"},
    211: {"en": "Krishnarajanagara", "kn": "ಕೃಷ್ಣರಾಜನಗರ"},
    212: {"en": "Hunsur", "kn": "ಹುಣಸೂರು"},
    213: {"en": "Heggadadevankote", "kn": "ಹೆಗ್ಗಡದೇವನಕೋಟೆ"},
    214: {"en": "Nanjangud", "kn": "ನಂಜನಗೂಡು"},
    215: {"en": "Chamundeshwari", "kn": "ಚಾಮುಂಡೇಶ್ವರಿ"},
    216: {"en": "Krishnaraja", "kn": "ಕೃಷ್ಣರಾಜ"},
    217: {"en": "Chamaraja", "kn": "ಚಾಮರಾಜ"},
    218: {"en": "Narasimharaja", "kn": "ನರಸಿಂಹರಾಜ"},
    219: {"en": "Varuna", "kn": "ವರುಣ"},
    220: {"en": "T. Narasipur", "kn": "ಟಿ.ನರಸೀಪುರ"},
    221: {"en": "Hanur", "kn": "ಹನೂರು"},
    222: {"en": "Kollegal", "kn": "ಕೊಳ್ಳೇಗಾಲ"},
    223: {"en": "Chamarajanagar", "kn": "ಚಾಮರಾಜನಗರ"},
    224: {"en": "Gundlupet", "kn": "ಗುಂಡ್ಲುಪೇಟೆ"},
}

import re

from download_rolls import AC_LIST_RAW


def _norm_en(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", (s or "").lower())


_EN_TO_KN = {_norm_en(v["en"]): v["kn"] for v in _CURRENT_AC_MASTER.values() if v.get("en")}

_MANUAL_KN = {
    _norm_en("Binnypet"): "ಬಿನ್ನಿಪೇಟೆ",
    _norm_en("Bharathinagar"): "ಭಾರತೀನಗರ",
    _norm_en("Jayamahal"): "ಜಯಮಹಲ್",
    _norm_en("Gulegud"): "ಗುಳೇಗುಡ್",
    _norm_en("Uchagaon"): "ಉಚಗಾಂವ",
    _norm_en("Bagewadi"): "ಬಾಗೇವಾಡಿ",
    _norm_en("Sankeshwar"): "ಸಂಕೇಶ್ವರ",
    _norm_en("Sadalga"): "ಸದಲಗಾ",
    _norm_en("Kurugodu"): "ಕುರುಗೋಡು",
}

AC_MASTER: dict[int, dict[str, str]] = {}
_last_name = ""
for _ln in AC_LIST_RAW.splitlines():
    ln = _ln.strip()
    if not ln:
        continue
    if ln.lower() in {"district", "constituency name", "assembly constituency number"}:
        continue
    if re.fullmatch(r"A\\d{3}", ln):
        ac = int(ln[1:])
        en = _last_name or f"AC-{ac}"
        key = _norm_en(en)
        kn = _EN_TO_KN.get(key) or _MANUAL_KN.get(key) or ""
        AC_MASTER[ac] = {"en": en, "kn": kn}
    else:
        _last_name = ln

if len(AC_MASTER) != 224:
    for i in range(1, 225):
        AC_MASTER.setdefault(i, {"en": f"AC-{i}", "kn": ""})


def get_ac_name(ac_num: int, lang="en") -> str:
    v = AC_MASTER.get(int(ac_num))
    if not v:
        return f"AC-{int(ac_num)}"
    return v.get(lang, v.get("en")) or f"AC-{int(ac_num)}"
