MUSLIM_TRIGGER_SUFFIXES_KN = [
    "ಖಾನ್",
    "ಬೇಗಂ",
    "ಬಾನು",
    "ಷೇಕ್",
    "ಶೇಖ್",
    "ಸಾಬ್",
    "ಸಾಹೇಬ್",
    "ಮಿಯಾ",
    "ಉಲ್ಲಾ",
    "ಅಲ್ಲಾ",
    "ಭಾಷ",
    "ಭಾಷಾ",
    "ಪಾಷ",
    "ಪಾಷಾ",
]

MUSLIM_TRIGGER_PREFIXES_KN = [
    "ಮೊಹಮದ್",
    "ಮಹಮದ್",
    "ಮಹ್ಯದ್",
    "ಅಬ್ಬುಲ್",
    "ಅಬ್ದುಲ್",
    "ಮೊಹಮ್ಮದ್",
    "ಶೇಖ್",
    "ಷೇಕ್",
    "ಸಯ್ಯದ್",
    "ಸ್ಯೆಯದ್",
    "ಇಬ್ರಾಹಿಂ",
    "ಇಸ್ಮಾಯೇಲ್",
    "ಹಸನ್",
    "ಹುಸೇನ್",
    "ಅಲಿ",
    "ಫಾತಿಮ",
    "ಆಯಿಶ",
    "ಖದೀಜ",
    "ಝೈನಬ್",
    "ರಶೀದ್",
    "ರಹೀಂ",
]

MUSLIM_TRIGGER_STANDALONE_KN = {
    "ಉಲ್ಲಾ",
    "ಬೇಗ",
    "ಮಿಯಾ",
}

MUSLIM_PHONEME_MAP = {
    "ph": "f",
    "bh": "b",
    "ja": "za",
    "ji": "zi",
    "jh": "z",
}

MUSLIM_NAME_CORRECTIONS = {
    "Abbuul": "Abdul",
    "Abbul": "Abdul",
    "Abddul": "Abdul",
    "Ibraahin": "Ibrahim",
    "Ibraahim": "Ibrahim",
    "Mehbub": "Mehboob",
    "Mahbub": "Mehboob",
    "Mohmmad": "Mohammad",
    "Mohamad": "Mohammad",
    "Mahammad": "Mohammad",
    "Mhammad": "Mohammad",
    "Mahyad": "Mohd",
    "Mahyadu": "Mohd",
    "Begam": "Begum",
    "Begamm": "Begum",
    "Banu": "Banu",
    "Khanum": "Khanum",
    "Shafiuulla": "Shafiullah",
    "Shafiulla": "Shafiullah",
    "Mansoorul": "Mansoorullah",
    "Rehaman": "Rehman",
    "Rehamana": "Rehman",
    "Rahiman": "Rahiman",
    "Fatiima": "Fatima",
    "Phatima": "Fatima",
    "Phayaaj": "Fayaz",
    "Phayaz": "Fayaz",
    "Jaheera": "Zaheera",
    "Jaheer": "Zaheer",
    "Zaheera": "Zaheer",
    "Jinaath": "Zinat",
    "Jinat": "Zeenat",
    "Sayyadd": "Syed",
    "Saiyad": "Syed",
    "Sayad": "Sayyad",
    "Khaadir": "Khadir",
    "Qaasim": "Qasim",
    "Mamthaaj": "Mumtaz",
    "Mammaj": "Mammaj",
    "Aayisha": "Ayisha",
    "Aisha": "Ayisha",
    "Rashiid": "Rasheed",
    "Raseeda": "Rasheeda",
    "Nusrath": "Nusrath",
    "Nusrat": "Nusrath",
    "Zulekhaa": "Zulekha",
    "Zulekha": "Zulekha",
    "Gulnaaz": "Gulnaz",
    "Shahanaaz": "Shahnaz",
    "Shabaan": "Shabaan",
    "Tabasumm": "Tabasum",
    "Parviin": "Parveen",
    "Parviina": "Parveen",
    "Parween": "Parveen",
    "Naziima": "Nazeema",
    "Naaziiya": "Naziya",
    "Nasiiya": "Nasiya",
    "Salmaa": "Salma",
    "Ameenulla": "Aminullah",
    "Aminuulla": "Aminullah",
    "Obaidulla": "Obaidullah",
    "Obaidu": "Obaid",
    "Khaleelull": "Khaleelullah",
    "Faazal": "Fazal",
    "Faazil": "Fazil",
    "Haleelu": "Haleelu",
    "Haliil": "Haleel",
    "Arjumaan": "Arjumana",
    "Arjumana": "Arjumana",
    "Nawshaad": "Nowshad",
    "Nowshaad": "Nowshad",
    "Kamarunnisa": "Kamarunnisa",
    "Kamarunniisa": "Kamarunnisa",
}

KAN_TITLECASE_LOWER_TOKENS = {"ul", "bin", "bint", "al"}

ULLA_JOIN_TOKENS = {"ulla", "ullah"}
